### ISSUE TITLE
Add Button TMP component for only text display

### ISSUE THREAD

**Issue by DucNV2000** [pancake-llc/foundation#115]

**Comment by yenmoc** [comment]
![image](https://github.com/pancake-llc/foundation/assets/44673303/644dae74-b94a-430e-9f5a-a29e6f3c9402)

In this [commit](https://github.com/pancake-llc/foundation/commit/f4d9516e62c0a2bc0424598a92435f9d4bb895b4) , RequireComponent Image has been removed. Now you can freely use UIButton with Text without necessarily needing an Image.
