### ISSUE TITLE
Venting: Apex is Bad on Listening to changes on ScriptableObject. `ScriptableVariableBase` was a lifesaver

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#116]
1. Apex doesn't let inspector update when any scriptable variable value is changed, but the `ScriptableVariableBase` was a lifesaver as it would let the update of scriptable object directly.

https://github.com/pancake-llc/foundation/assets/63500913/ac96b3fa-9aa4-4df7-aeee-53d2b82c27ce

2. Scriptable Base also provided the ability to have a peak of the variable value without have to open the drop-down to see the value.

3. Currently, No `ScriptableVaraible` is viewable in Apex → `Array` Attribute
![image](https://github.com/pancake-llc/foundation/assets/63500913/600526b6-39be-402a-a23a-b3264e193f65)

**Comment by yenmoc** [comment]
3. Displaying scriptable Input event information seems unnecessary (so far I have not seen a case where I need to use the Raise button for these events) so I have removed the scriptable input drawer in this ơcommit](https://github.com/pancake-llc/foundation/commit/459453a633ac2c44b9d3c633f1d45dbc6697bc79) and before this script. which has not done anything yet

now it will look like this

![image](https://github.com/pancake-llc/foundation/assets/44673303/c6b9f924-7d22-4632-8b6f-27be9b993ed3)

**Comment by yenmoc** [comment]
1. I'll try to find a way to make it work, maybe calling Repaint isn't enough

**Comment by IAFahim** [comment]
Thank you kind Sir, for taking a look into this matter. God bless you.

**Comment by yenmoc** [comment]
1. Done, now do not cache editor to fetch directly value of scriptable (It will affect performance in case the scriptable's data uses resource-intensive attributes such as NamePickupAttribute) [see changed in commit](https://github.com/pancake-llc/foundation/commit/cc88807e38dcf96779c662a3ee779a2ce7872c95)

**Comment by yenmoc** [comment]
2. Done, add draw preview single value of scriptable with name property specify is value

**Comment by yenmoc** [comment]
@IAFahim Try checking again to see if it works for you?

**Comment by IAFahim** [comment]
Works perfectly. Freezing, the whole scriptable object view was quite nice. Now the inspector view of scriptable view and scriptable object view looks same, So changing stuff on both view is more fun.

You are quite something. Thank you, Sir.
