### ISSUE TITLE
Bug in Prime Tween, Need help reporting 

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#126]
There is a local transform bug for sequence in Prime Tween 

https://github.com/KyryloKuzyk/PrimeTween/issues/63#issuecomment-2041594198

The author was asking which version of Prime Tween we are using. As on last update of Prime Tween there is no mention of version, I can't answer the question yet. Could you be so kind to tell the version on last update. 

https://github.com/pancake-llc/foundation/commit/12f7a2eb0dea03f9c72a0e547e5ecce667c7c585

**Comment by yenmoc** [comment]
In foundation currently using version 1.1.14

**Comment by yenmoc** [comment]
I will update to lastest version 1.1.15

**Comment by IAFahim** [comment]
The bug in Prime Tween is fixed, can you update it to 1.16 please.

**Comment by yenmoc** [comment]
Done
