### ISSUE TITLE
Set iOS App Pause On Background

### ISSUE THREAD

**Issue by VirtueSky** [pancake-llc/foundation#127]
// On Android, Unity is paused when displaying interstitial or rewarded video.
 // This setting makes iOS behave consistently with Android.
            `MobileAds.SetiOSAppPauseOnBackground(true);`

**Comment by yenmoc** [comment]
Thanks, I will add it soon

**Comment by yenmoc** [comment]
add in this [commit 662825a](https://github.com/pancake-llc/foundation/commit/662825a76095f413e389ff8049ad0ee686c5e99b)
