### ISSUE TITLE
Iap not auto restore purchase (android)

### ISSUE THREAD

**Issue by DucNV2000** [pancake-llc/foundation#131]
method `PurchaseProcessingResult ProcessPurchase(PurchaseEventArgs buyEvent)` does not call when reinstalling game in version Heart 2.x

**Comment by yenmoc** [comment]
fixed in v3 [28bd764](https://github.com/pancake-llc/foundation/commit/28bd764ccc3a7fe7d255b45afab12facd8710b05)

**Comment by yenmoc** [comment]
Checking whether the product has been purchased or not to enforce the return of the item's contents will be executed each time the `IAPManager` is initialized so you need to check in the code that handles inherit form `IAPurchaseSuccess` to ensure it is only execute only once
