### ISSUE TITLE
[v3.0] Pool Doesn't handle Prewarm or Return Properly

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#132]
When you try to `Return` without calling the `Request()` it gives error
Error: The given key 'xxx (UnityEngine.GameObject)' was not present in the dictionary.

Even if you call `Prewarm` it still doesn't add it to CloneReferences
Resulting in same Error: The given key 'xxx (UnityEngine.GameObject)' was not present in the dictionary.

https://github.com/pancake-llc/foundation/assets/63500913/87db60db-eb10-4184-94a2-7eba57653419

https://github.com/IAFahim/Citadel

**Comment by yenmoc** [comment]
I will check it out tonight

**Comment by yenmoc** [comment]
After a quick check, it seems you are trying to Return an object from the pool without using Request, I don't understand why you are doing that when the prerequisite is that you need to take an object from the pool then use it if you (why are you still referencing the object when it has already been returned to the pool, if you cache it somewhere you will need to reset the reference to null). As for the internal handle code itself for this purpose, I find it confusing and difficult to implement. You will need OnEnabled and OnDisabled handles by default to check if the object is active without calling Request or not? This will have the consequence that it requires the prefab source to attach additional components

**Comment by yenmoc** [comment]
It will be slightly different from 2.x, since we always need to create a source version that is always poolable

**Comment by IAFahim** [comment]
I made the scene to show prewarm doesn't create a pool. And enabled it manually to try to mimic how it would behave.

Let's say i want to test out if a prefab works or not, Instead of drag and dropping it on inspector and hitting play, i would have to call Request and from other script to know if it works or not.

If you suggest that using Request. Than it's absolutely fine, as you have more experience with unity, so this way must be better. I was reported it because it was different from 2.x

**Comment by yenmoc** [comment]
It is not recommended, turning on gameObject manually like that in 2.x has a potential bug where I did not check duplicate when pushing it back to pool x as a result the pool will increase by elements even though the element That's already in the pool. It's like sneaking past the ticket counter at a water park :)))) quite risky

**Comment by IAFahim** [comment]
A really nice explanation. Thank you, Sir. I am marking it as closed as complete.
