### ISSUE TITLE
Error ApplovinAdClient when update max sdk 7.0.0

### ISSUE THREAD

**Issue by DucNV2000** [pancake-llc/foundation#138]
- Missing Api `MaxSdk.SetIsAgeRestrictedUser`

https://github.com/pancake-llc/foundation/blob/50204c4b2b42c84a85b570f7faef9b605c21b5b3/Assets/Heart/Modules/Advertising/Client/ApplovinAdClient.cs#L14

**Comment by aprius** [comment]
Fixed in version 3.0.5, SetIsAgeRestrictedUser was be removed to be compabile with prohibition on Children Data or Using the Services for Children or Apps Exclusively Targeted to Children
