### ISSUE TITLE
Can't put ScriptableObject in any kind of Serialized dictionary (nor Odin ones nor custom ones). Is it intentional?

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#139]
NullReferenceException: Object reference not set to an instance of an object
PancakeEditor.ScriptableObjectPropertyDrawer.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at Assets/Heart/Core/Editor/Drawer/ScriptableObjectPropertyDrawer.cs:26)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <82d5427af9d84542ac1bab8e50c139c7>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.Rect visibleArea) (at <82d5427af9d84542ac1bab8e50c139c7>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <82d5427af9d84542ac1bab8e50c139c7>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <321eb2db7c6d43ea8fc39b54eaca3452>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Sirenix.OdinInspector.Editor.UnityPropertyHandlerUtility.PropertyHandlerOnGUI (System.Object handler, UnityEngine.Rect rect, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.AbstractTypeUnityPropertyDrawer`3[TDrawer,TDrawnType,T].DrawPropertyLayout (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.OdinDrawer.CallNextDrawer (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.Validation.ValidationDrawer`1[T].DrawPropertyLayout (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.OdinDrawer.CallNextDrawer (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.Drawers.PropertyContextMenuDrawer`1[T].DrawPropertyLayout (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.OdinDrawer.DrawProperty (UnityEngine.GUIContent label) (at <27a079271f234793a393385e1e6e9f73>:0)
Sirenix.OdinInspector.Editor.InspectorProperty.Draw (UnityEngine.GUIContent defaultLabel) (at <27a079271f234793a393385e1e6e9f73>:0)
Rethrow as OdinPropertyException: This error occurred while being drawn by Odin.
Current IMGUI event: Ignore
Odin Property Path: _dictionary.{"f6461c91a7ad485"}
Odin Drawer Chain:
> PropertyContextMenuDrawer<Weapon>
> NonSerializedShowInInspectorWarningAttributeDrawer
> ValidationDrawer<Weapon>
> AbstractTypeUnityPropertyDrawer<ScriptableObjectPropertyDrawer, ScriptableObject, Weapon>
> AbstractTypeUnityPropertyDrawer<RenameableObjectPropertyDrawer, Object, Weapon>
> UnityObjectDrawer<Weapon>
> CompositeDrawer.
UnityEngine.Debug:LogException(Exception)
Sirenix.OdinInspector.Editor.InspectorProperty:Draw(GUIContent)
Sirenix.OdinInspector.Editor.Drawers.DictionaryDrawer`3:D

**Comment by aprius** [comment]
Okay I will check it after a lunch time

**Comment by aprius** [comment]
everything work oke, what code are you using?

![image](https://github.com/user-attachments/assets/dd6e32fd-cd27-4880-935f-d058cae6cf89)

there was a bug when pressing the create scriptable button when it was a value and i just fixed it

**Comment by IAFahim** [comment]
Now magically it works. Thank you sir.
