### ISSUE TITLE
Sir, do you know about new `Object.InstantiateAsync` in unity 6

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#141]
I just found out from here:
https://github.com/keijiro/InstantiateAsyncTest?tab=readme-ov-file

Prewarm for pooling can become really powerful.

**Comment by aprius** [comment]
Yeah it's a great API, I tested it a while back, it's a testament to the async era. You can now use it as an optimization technique for generating heavy objects without having to worry too much about when they're generated like dynamically loading maps...

**Comment by aprius** [comment]
Yaa, using it in prewarm pool will be really effective and of course it also comes with RequestAsync

**Comment by IAFahim** [comment]
Of course you had checked it before 🥲 and I thought I have a new information. But I don't understand how you could have known about it because its only available on unity 6.1 

https://docs.unity3d.com/6000.1/Documentation/ScriptReference/Object.InstantiateAsync.html

And about RequestAsync it's there on the documents on unity site(I might not know how to look that good)

**Comment by aprius** [comment]
No, It was added since unity 2022.3.20

**Comment by IAFahim** [comment]
Ehh bad unity website documentation design. 

![Screenshot_2024-11-04-14-56-11-813_org mozilla firefox~2](https://github.com/user-attachments/assets/4eea0dd0-b9ef-496b-bbb3-f9796187bca7)

Thank you Sir for your guidance. You always know a lot, and helpful.

**Comment by aprius** [comment]
I just tried brenchmarking between `Instantiate` and `InstantiateAsync` but maybe this visual explanation is too obvious [here](https://x.com/_kzr/status/1851968293823001009). And there is no problem if calling `Request` or `Return` while `PrewarmAsync` is not completed

**Comment by aprius** [comment]
```csharp
    public GameObject prefab;

    private void Start()
    {
        prefab.PrewarmAsync(10, 10).Forget();
    }
```

**Comment by IAFahim** [comment]
Thank you for explanation, Sir.

> ```cs
>     public GameObject prefab;
> 
>     private void Start()
>     {
>         prefab.PrewarmAsync(10, 10).Forget();
>     }
> ```

Isn't the second parameters in PrewarmAsync a `CancellationToken` in this repo. Are a you trying out a new method?

**Comment by aprius** [comment]
The prewarm method previously available for `IAsyncObjectPool` with the existing async implementations will be no different, the new Prewarm method added for `SharedGameObjectPool` and `GameObjectPool` which implements the utility APIs for GameObject

**Comment by aprius** [comment]
Maybe I'll add CancellationToken to it too
