### ISSUE TITLE
Does `SharedAssetReferenceGameObjectPool` makes sense?

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#142]
Link in a game let's assume that there are 20 Enemy Type.
We have a `Prefab` `of 20 Enemy Type` in a list. Not all enemy gets spawned.  
I have heard unity loads those 20 prefab in memory.

And let's assume we just have `AssetReference` we create pool from them like `SharedGameObjectPool` → `SharedAssetReferenceGameObjectPool`. Is it a bad idea?

I am thinking of using addressable instead of prefab reference. Is that bad idea? As unity announced in unity 2024 smaller addressable are now preferred way.
https://youtu.be/wvcdHrrQIu4?si=w1to1AETbZenGTuk&t=984

Like this
```csharp
using System.Collections.Generic;
using Pancake.Pools;
using UnityEngine;
using UnityEngine.AddressableAssets;

namespace Soul.Pools.Runtime
{
    public static class SharedAssetPool
    {
        private static readonly Dictionary<AssetReferenceGameObject, AddressableGameObjectPool> Pools = new();

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void Init()
        {
            ClearAll();
            Pools.Clear();
        }

        public static GameObject Request(AssetReferenceGameObject original)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            return GetOrCreatePool(original).Request();
        }

        public static GameObject Request(AssetReferenceGameObject original, Transform parent)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            return GetOrCreatePool(original).Request(parent);
        }

        public static GameObject Request(AssetReferenceGameObject original, Transform parent,
            bool instantiateInWorldSpace)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            var gameObject = GetOrCreatePool(original).Request();
            gameObject.transform.SetParent(parent, instantiateInWorldSpace);
            return gameObject;
        }

        public static GameObject Request(AssetReferenceGameObject original, Vector3 position, Quaternion rotation)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            return GetOrCreatePool(original).Request(position, rotation);
        }

        public static GameObject Request(AssetReferenceGameObject original, Vector3 position, Quaternion rotation,
            Transform parent)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            return GetOrCreatePool(original).Request(position, rotation, parent);
        }

        public static void Return(AssetReferenceGameObject original, GameObject gameObject)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            if (gameObject == null) throw new System.ArgumentNullException(nameof(gameObject));
            GetOrCreatePool(original).Return(gameObject);
        }

        public static void ClearAll(AssetReferenceGameObject original)
        {
            if (original == null) throw new System.ArgumentNullException(nameof(original));
            GetOrCreatePool(original).Clear();
        }

        public static void ClearAll()
        {
            foreach (var pool in Pools.Values) pool.Clear();
        }

        private static AddressableGameObjectPool GetOrCreatePool(AssetReferenceGameObject original)
        {
            if (Pools.TryGetValue(original, out var pool)) return pool;
            pool = new AddressableGameObjectPool(original);
            Pools.Add(original, pool);

            return pool;
        }
    }
}
```

**Comment by IAFahim** [comment]
Also should there be changes in `Request` methods in `AddressableGameObjectPool` to use `while(true)` like `SharedGameObjectPool`

https://github.com/pancake-llc/foundation/blob/ae969f31bced3111b1d0e3f5271dbd542a95ed58/Assets/Heart/Modules/Pool/Addressables/AddressableGameObjectPool.cs
```
        public GameObject Request()
        {
            ThrowIfDisposed();

            if (!_stack.TryPop(out var obj))
            {
                obj = Addressables.InstantiateAsync(_key).WaitForCompletion();
            }
            else
            {
                obj.SetActive(true);
            }

            PoolCallbackHelper.InvokeOnRequest(obj);
            return obj;
        }
```

**Comment by aprius** [comment]
@IAFahim I have always used Addressable instead of Resources since it came out. while true in `Request` of SharedGameObjectPool is unnecessary because the logic can be simplified to achieve the same result without looping.

**Comment by aprius** [comment]
> Link in a game let's assume that there are 20 Enemy Type. We have a `Prefab` `of 20 Enemy Type` in a list. Not all enemy gets spawned. I have heard unity loads those 20 prefab in memory.
> 
> And let's assume we just have `AssetReference` we create pool from them like `SharedGameObjectPool` → `SharedAssetReferenceGameObjectPool`. Is it a bad idea?
> 
> I am thinking of using addressable instead of prefab reference. Is that bad idea? As unity announced in unity 2024 smaller addressable are now preferred way. https://youtu.be/wvcdHrrQIu4?si=w1to1AETbZenGTuk&t=984
> 
> Like this
> 
> ```cs
> using System.Collections.Generic;
> using Pancake.Pools;
> using UnityEngine;
> using UnityEngine.AddressableAssets;
> 
> namespace Soul.Pools.Runtime
> {
>     public static class SharedAssetPool
>     {
>         private static readonly Dictionary<AssetReferenceGameObject, AddressableGameObjectPool> Pools = new();
> 
>         [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
>         private static void Init()
>         {
>             ClearAll();
>             Pools.Clear();
>         }
> 
>         public static GameObject Request(AssetReferenceGameObject original)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             return GetOrCreatePool(original).Request();
>         }
> 
>         public static GameObject Request(AssetReferenceGameObject original, Transform parent)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             return GetOrCreatePool(original).Request(parent);
>         }
> 
>         public static GameObject Request(AssetReferenceGameObject original, Transform parent,
>             bool instantiateInWorldSpace)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             var gameObject = GetOrCreatePool(original).Request();
>             gameObject.transform.SetParent(parent, instantiateInWorldSpace);
>             return gameObject;
>         }
> 
>         public static GameObject Request(AssetReferenceGameObject original, Vector3 position, Quaternion rotation)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             return GetOrCreatePool(original).Request(position, rotation);
>         }
> 
>         public static GameObject Request(AssetReferenceGameObject original, Vector3 position, Quaternion rotation,
>             Transform parent)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             return GetOrCreatePool(original).Request(position, rotation, parent);
>         }
> 
>         public static void Return(AssetReferenceGameObject original, GameObject gameObject)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             if (gameObject == null) throw new System.ArgumentNullException(nameof(gameObject));
>             GetOrCreatePool(original).Return(gameObject);
>         }
> 
>         public static void ClearAll(AssetReferenceGameObject original)
>         {
>             if (original == null) throw new System.ArgumentNullException(nameof(original));
>             GetOrCreatePool(original).Clear();
>         }
> 
>         public static void ClearAll()
>         {
>             foreach (var pool in Pools.Values) pool.Clear();
>         }
> 
>         private static AddressableGameObjectPool GetOrCreatePool(AssetReferenceGameObject original)
>         {
>             if (Pools.TryGetValue(original, out var pool)) return pool;
>             pool = new AddressableGameObjectPool(original);
>             Pools.Add(original, pool);
> 
>             return pool;
>         }
>     }
> }
> ```


I think `SharedAddressableGameObjectPool` is nice

**Comment by IAFahim** [comment]
> @IAFahim I have always used Addressable instead of Resources since it came out. while true in Request of SharedGameObjectPool is unnecessary because the logic can be simplified to achieve the same result without looping.

Thank you, Sir. I was having this thought for a long time. As in this project it was always `Gameobject` pool based. I always thought addressable pool system on might be bad and thought I might be missing something about it, or you would have created something already in the repo. Thank you, Sir, for clarifying it.

I again created issue instead of opening it on discussion, sorry for that. I would try to keep it on discussion. 

> I think SharedAddressableGameObjectPool is nice

Thank you, Sir. It was my first code review. May god help you for your kindness.

**Comment by aprius** [comment]
I added it in update [3.1.3](https://github.com/pancake-llc/foundation/releases/tag/3.1.3)
