### ISSUE TITLE
Opening clean `foundation` project give exception loading ``Pancake.Localization.LocaleSettings`

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#143]
Exception: Scriptable setting for Pancake.Localization.LocaleSettings must be create before run!. Please find and setup it in wizard!
Pancake.ScriptableSettings`1[T].get_Instance () (at Assets/Heart/Core/Runtime/Scriptable/ScriptableSettings.cs:17)
Pancake.Localization.LocaleSettings.get_AvailableLanguages () (at Assets/Heart/Modules/Localization/Runtime/LocaleSettings.cs:19)
Pancake.Localization.LocaleVariable`1[T].get_Value () (at Assets/Heart/Modules/Localization/Runtime/Implement/Variable/LocaleVariable.cs:36)
Pancake.Localization.LocaleComponent.GetValueOrDefault[T] (Pancake.Localization.LocaleVariable`1[T] variable) (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleComponent.cs:37)
Pancake.Localization.LocaleComponentGeneric`2[TVariable,T].GetLocaleValue () (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleComponentGeneric.cs:23)
Pancake.Localization.LocaleTextComponent.GetLocaleValue () (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleTextComponent.cs:28)
Pancake.Localization.LocaleComponentGenericBase.TryUpdateComponentLocalization (System.Boolean isOnValidate) (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleComponentGenericBase.cs:90)
Pancake.Localization.LocaleComponent.ForceUpdate () (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleComponent.cs:22)
Pancake.Localization.LocaleComponent.OnValidate () (at Assets/Heart/Modules/Localization/Runtime/Implement/Behaviour/LocaleComponent.cs:42)

![image](https://github.com/user-attachments/assets/6fea58e6-1a8f-44a4-ba94-a1f1b877538a)

**Comment by IAFahim** [comment]
- [x] builds
- [x] App plays
- [x] Language Switches in App play mode

**Comment by aprius** [comment]
error message seems annoying, i will fix it soon

**Comment by aprius** [comment]
fixed in this [commit](https://github.com/pancake-llc/foundation/commit/c3ca21f44083ddfd4f57378900cdf0e6b8cff2cf)
