### ISSUE TITLE
Game frizzes if transition is interpreted

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#49]
If you go from [menu](https://github.com/pancake-llc/foundation/blob/main/Assets/_Root/Scenes/menu.unity) scene to [gameplay](https://github.com/pancake-llc/foundation/blob/main/Assets/_Root/Scenes/gameplay.unity) scene too quickly before transition is over, you get an error and game frizzes.

**Comment by yenmoc** [comment]
Can you describe more clearly? The transition hasn't ended yet, it still prevents the user from seeing the level generated in gameplay, so where do frizzes happen?

**Comment by yenmoc** [comment]
Previously, the loading scene was jerky because the scene was loaded from an addressable, so I added a transition to hide that phenomenon

**Comment by yenmoc** [comment]
Did you check on the latest commit?

**Comment by IAFahim** [comment]
https://github.com/pancake-llc/foundation/assets/63500913/6982e358-41c4-4e4a-846f-7152d42c20a7

ArgumentException: An item with the same key has already been added. Key: SceneTransitionPopup
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eef08f56e2e042f1b3027eca477293d9>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eef08f56e2e042f1b3027eca477293d9>:0)
Pancake.UI.PopupContainer+<PushRoutine>d__42.MoveNext () (at Assets/Heart/Modules/UGUI/Runtime/Screen/Popup/PopupContainer.cs:298)
Pancake.GlobalComponent+<ProcessRoutine>d__47.MoveNext () (at Assets/Heart/Core/Runtime/GlobalComponent.cs:176)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <56073df97ede4f769c2cc45d546d986d>:0)

**Comment by IAFahim** [comment]
> Did you check on the latest commit?
I just did. Even settings when it's in transition it shows error.

ArgumentException: An item with the same key has already been added. Key: SettingPopup
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eef08f56e2e042f1b3027eca477293d9>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eef08f56e2e042f1b3027eca477293d9>:0)
Pancake.UI.PopupContainer+<PushRoutine>d__42.MoveNext () (at Assets/Heart/Modules/UGUI/Runtime/Screen/Popup/PopupContainer.cs:298)
Pancake.GlobalComponent+<ProcessRoutine>d__47.MoveNext () (at Assets/Heart/Core/Runtime/GlobalComponent.cs:176)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <56073df97ede4f769c2cc45d546d986d>:0)

**Comment by IAFahim** [comment]
And I am trying to maintain a fork of your repo with URP.
But the problem is I can't show the admin panel and coin PopUp on top of menu or gameplay camera.

And again, thank you for creating this brilliant thing. You are awesome.

**Comment by yenmoc** [comment]
Okay thanks for information, I will check it now

**Comment by yenmoc** [comment]
After checking for a while, I found there were no problems on my computer at home or at the company. In the video, I can see that the transition in the scene is still running, but in the gameplay scene, it is no longer there, you Are there any edits to the camera or popup display?

**Comment by yenmoc** [comment]
https://github.com/pancake-llc/foundation/assets/44673303/3598b446-a764-4464-b462-c3ad23f9b94e

**Comment by IAFahim** [comment]
The reason it happens in the first place is because of Switching to URP.
_(I took your project converted to URP to maintain a fork of URP and just added [SimpleFolderIcon](https://github.com/SeaeeesSan/SimpleFolderIcon))_

The URP camera doesn't act similar to old-RP. Problem is, when you click something twice and PopUp goes to transition, you still get to click the same button as the screen doesn't get block and popup showed on a different camera. So it complains that the popup is still in transition, invoking that creates the error.

It's a default URP camera system problem, not this library problem.
