### ISSUE TITLE
TextMeshPro Deprecated from 2023.2 

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#51]
TextMeshPro Merged With UGUI So adding this line should make it future-proof As 2023 is close.

**Source:**
https://forum.unity.com/threads/2023-2-latest-development-on-textmesh-pro.1434757/

**Suggested:**
```csharp
#if UNITY_2023_1
using TMPro;
#else
using UnityEngine.UI;
#endif
``` 

Love your work, BTW. You are awesome.

**Comment by yenmoc** [comment]
Yes, I also know that TMP will soon be integrated into Unity 2023.2, so I am also preparing to upgrade the project to Unity 2023 to test and ensure it will be compatible with Unity 6.

**Comment by yenmoc** [comment]
I tried opening foundation with unity 2023.2f1 to test. And it seems that they only moved TextMeshPro into the UGUI package, the namespace will still be retained. The previous TextMeshPro package will be deleted and only a window will appear so you can re-install the necessary resources. This means you can open it with unity 2023 without any problems

**Comment by IAFahim** [comment]
The Unity Version I tested 2023.2.1f game me lots of error About TMPRO when I imported The heart Package, But on 2023.2.3f1 It's showing no error about the name space. Thank you for still keeping this issue open as I got to test it on higher version. 

## Its all Okay
Thank you
