### ISSUE TITLE
In audio pool, First 10 Initialized item of the pool never gets used

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#58]
![image](https://github.com/pancake-llc/foundation/assets/63500913/747474ba-88f8-4722-8823-296a56adf542)
![image](https://github.com/pancake-llc/foundation/assets/63500913/717ae8a1-695b-45ec-9e75-7d81f89e6f9e)
![image](https://github.com/pancake-llc/foundation/assets/63500913/9d007f22-c00d-4283-a5c6-5a4b3bebcf78)

**Comment by yenmoc** [comment]
Yes, this is a bug where the pool container is cleared every time the scene loads. I will fix it

**Comment by yenmoc** [comment]
fixed in #59
