### ISSUE TITLE
Conflict with Wizard Shortcut

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#60]
`Shift+W` conflicts, while playing game trying to move around with Wizard Shortcut
Context: `Shift+W` moves around camera faster
Suggested Shortcut `Ctrl+W`

Ow ow and I use `Shift+V` for scriptable Variables

https://github.com/pancake-llc/foundation/assets/63500913/0b3d7ae5-bb15-43b1-b5c5-4b0c5d049576

**Comment by yenmoc** [comment]
You can use shortcut Alt + 1 to quick open panel create scriptable. Okay I'll think about to shortcut open Wizard

**Comment by IAFahim** [comment]
Alt+1..4 is taken by unity in new update of 2023.2.3f (or even below maybe) 

https://github.com/pancake-llc/foundation/assets/63500913/93a5492f-83a7-4556-a411-4191a3288593

**Comment by yenmoc** [comment]
Can you tell me which 3rd party package you are using? My toolbar in Unity is a bit different from yours. By the way, I'm using version 2022.3.12f1

![image](https://github.com/pancake-llc/foundation/assets/44673303/a49ced3e-ad8b-4565-abed-f2472d05fd03)

**Comment by yenmoc** [comment]
![image](https://github.com/pancake-llc/foundation/assets/44673303/8223d6d3-fda3-4293-b135-3d62a83b76b6)

**Comment by yenmoc** [comment]
The behavior of pressing shift + arrow to move faster in the scene view is a predefined behavior of unity. It is not a conflict of the shortcut, if you want to open the wizard panel while moving the arrow like that I think you should Opening the wizard and dragging it to the side would be more reasonable. The key combination ctrl + shift + w is also a good idea, but pressing 3 buttons seems a bit annoying, especially when pressing with one hand like that, besides The fast scrolling behavior can still happen if you press shift before ctrl

**Comment by IAFahim** [comment]
> Can you tell me which 3rd party package you are using? My toolbar in Unity is a bit different from yours. By the way, I'm using version 2022.3.12f1
> 
> ![image](https://private-user-images.githubusercontent.com/44673303/292355970-a49ced3e-ad8b-4565-abed-f2472d05fd03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjAwNDksIm5iZiI6MTcwMzIxOTc0OSwicGF0aCI6Ii80NDY3MzMwMy8yOTIzNTU5NzAtYTQ5Y2VkM2UtYWQ4Yi00NTY1LWFiZWQtZjI0NzJkMDVmZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZDU4OTBiYWE2ZWUxYjlhNDkwOWI1OGM4YjUxNTAzYmJkOTI4Yjg2ZDY3YTE1MGUyZDM1YWYzMDFjYzI3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wMIS8N8j2fyBxCasPdO6x_Fzfc4_oZuzLe2MQDvxbHE)

Its just default project in unity 2023.2.3f1. No 3rd party asset.

**Comment by IAFahim** [comment]
> The behavior of pressing shift + arrow to move faster in the scene view is a predefined behavior of unity. It is not a conflict of the shortcut, if you want to open the wizard panel while moving the arrow like that I think you should Opening the wizard and dragging it to the side would be more reasonable. The key combination ctrl + shift + w is also a good idea, but pressing 3 buttons seems a bit annoying, especially when pressing with one hand like that, besides The fast scrolling behavior can still happen if you press shift before ctrl

Sorry i made a mistake in writing, It conflicts in `Game tab`. In game shift+W is used for sprinting.

**Comment by yenmoc** [comment]
Okay thank, i will checking in unity 2023

**Comment by yenmoc** [comment]
![image](https://github.com/pancake-llc/foundation/assets/44673303/db412cf1-9bf2-4f41-be4b-eb2a00ba2bd1)
![image](https://github.com/pancake-llc/foundation/assets/44673303/7b887990-61ef-4735-9f26-82d9fe0523c5)
by default ctrl + ... and alt + ... are not available.

I think use shift + ... for all  and we will compromise with acceleration in the scene view.

**Comment by IAFahim** [comment]
For any kind of game that requires sprinting `shift + W` would create complications. For that it can be `Ctrl+W`. 

For scene switching it can be `Shift+1...3`

I am just suggesting. If it's not of liking it's ok to stay as it is 😌

**Comment by yenmoc** [comment]
Update in pr #63
