### ISSUE TITLE
Spelling Mistake on method name `ToSnackCase` → `ToSnakeCase`

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#65]
![image](https://github.com/pancake-llc/foundation/assets/63500913/2704b23d-c044-46e4-b7a6-28ed5dd243dd)

**Comment by IAFahim** [comment]
Made a pull request for those 5 files #66

**Comment by yenmoc** [comment]
Well thank you obviously a typo. You can recreate another pull request, but I have already replied to your current pull request

**Comment by IAFahim** [comment]
> Well thank you obviously a typo. You can recreate another pull request, but I have already replied to your current pull request

Thank you for being so kind and waiting for a pull request that you can solve within a second. Thank you for inspiring others.

**Comment by IAFahim** [comment]
Fixed in #66
