### ISSUE TITLE
Asking `[SerializeField, TextArea(3, 6)] private string developerDescription` if it's not required to be shipped in game. Why not wrapping it with `#if UNITY_EDITOR`

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#74]
![image](https://github.com/pancake-llc/foundation/assets/63500913/7c78b16f-a6f6-4345-abdc-c38fe44b72c9)

With due respect Sir, I would like to know why did you opt for this approach. 

example

```csharp
namespace Pancake.Tracking
{
    using UnityEngine;

    public abstract class ScriptableTracking : ScriptableObject, ITracking
    {
        [SerializeField, TextArea(3, 6)] private string developerDescription;

        public abstract void Track();
    }
}
```

**Comment by yenmoc** [comment]
The explanation for this is that at that time I did not use #if UNITY_EDITOR to avoid runtime error `ScriptableObject has a different serialization layout when loading. Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?`

**Comment by yenmoc** [comment]
https://github.com/roboryantron/Unite2017/issues/11

**Comment by IAFahim** [comment]
I checked it, and you are right, Sir. Even unity uses the same code as you in their demo projects.

https://github.com/UnityTechnologies/PaddleGameSO/blob/e82bf3b59eaa9cf21a2445c0e61c011757ebbd7e/Assets/Core/Utilities/ScriptableObjects/DescriptionSO.cs#L9

Thank you for explaining the issue. I am grateful.
