### ISSUE TITLE
Prepare for switch to using nuget in next gen .NET in Unity 6

### ISSUE THREAD

**Issue by yenmoc** [pancake-llc/foundation#79]
Using Nuget will probably be more popular and easier than the current process when all Microsoft packages are pushed here.

- [ ] Split using nuget package

**Comment by IAFahim** [comment]
I couldn't find any article on nugget and unity 6. Was there any announcement about this topic.

**Comment by yenmoc** [comment]
This is a prediction, because unity moving to CLR core and using the latest .NET environment, using packages available on nuget will bring many benefits in addition to using nuget is quite convenient even though I have only tried the [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) package
