### ISSUE TITLE
Missing Feature?

### ISSUE THREAD

**Issue by yenmoc** [pancake-llc/foundation#80]
Should I add any essential features for game development in general?

**Comment by IAFahim** [comment]
Features I could find after thinking really really hard (as your heart has almost everything)

1. https://github.com/madsbangh/EasyButtons passing parameters to method and having different return type other than void.
2. Ui manget to support 3D position 
3. A list of all data saved by Data.Save and modify them in editor
4. Asking to save before loading screen when you hit playmode in example project.
5. Range slider for FloatVariable and IntVaraible if ranged is true.
6. https://github.com/pancake-llc/foundation/wiki/Bag Bag variable be serializable and probability being viewed like `LOD` or `Gradient` view in Unity Inspector
7. Scriptable Wizard window be open as on top always like addressable window does.
8. Scriptable object to have a button near it to open in floating inspector mode or in Scriptable Wizard.
9. A settings to remember the additive scenes hierarchy state and open it the same way it was editmode as in playmode. (Or auto expanding all the scenes children's. Cuz unity forgets every time and have to dive back in to edit basic stuff over and over)

And documentation on why use GameComponent Over MonoBehavior and example of update and other method and workflow compared to App.Update. (I also want to know how to access OnEnable or OnDisable or similar on GameComponent).

But at end super hugeeee love for you sir. May god repay you for all your hard work provided so far.

**Comment by yenmoc** [comment]
great, I will see and implement them as soon as possible.  Regarding `Data.Save`, data is serialized as byte[] to achieve high speed when loading and saving. Serialized data also does not include the type of data, so when deserializing we do not have enough information about type T to do that. I would try thinking about including the type of the data when serializing.

**Comment by yenmoc** [comment]
4. Asking to save before loading screen when you hit playmode in example project.  Done with #81

**Comment by yenmoc** [comment]
5. Range slider for FloatVariable and IntVaraible if ranged is true. Done with #82

**Comment by yenmoc** [comment]
2. `Ui manget to support 3D position`. Can you give an example of a specific case where you need to use it? Or do you mean sucking 3D items onto the UI?

**Comment by IAFahim** [comment]
>>2. Ui manget to support 3D position

> 2. `Ui manget to support 3D position`. Can you give an example of a specific case where you need to use it? Or do you mean sucking 3D items onto the UI?

Currently, we can only pass `Vector2D` to the position of spawned CoinFx which gets attracted to UI in world space. It would be quite handy to show the CoinFx going from 3D position to UI. Mainly if the camera is at 45 degree X rotation the coin pool illusion breaks as it only works in 2D not considering the Z position.

**Comment by IAFahim** [comment]
>>3. A list of all data saved by Data.Save and modify them in editor

> Regarding Data.Save, data is serialized as byte[] to achieve high speed when loading and saving. Serialized data also does not include the type of data, so when deserializing we do not have enough information about type T to do that. I would try thinking about including the type of the data when serializing.

We can have a field for Saved on Scriptable Wizard instead
![image](https://github.com/pancake-llc/foundation/assets/63500913/b2ac08aa-496e-4b6d-b13a-9efd8b168834)

Also, the panel isn't resizable and having a long name moves the star really far away, so a bit more spacing would be helpful in that case

**Comment by IAFahim** [comment]
Sir, the UI is not that visible in light mode

![image](https://github.com/pancake-llc/foundation/assets/63500913/a5c7d966-9775-4869-8340-71b53b3ddc21)

**Comment by yenmoc** [comment]
8. Scriptable object to have a button near it to open in floating inspector mode or in Scriptable Wizard. Done in #88

**Comment by yenmoc** [comment]
> Sir, the UI is not that visible in light mode
> 
> ![image](https://private-user-images.githubusercontent.com/63500913/296829407-a5c7d966-9775-4869-8340-71b53b3ddc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDE3MzQsIm5iZiI6MTcwNTM0MTQzNCwicGF0aCI6Ii82MzUwMDkxMy8yOTY4Mjk0MDctYTVjN2Q5NjYtOTc3NS00ODY5LTgzNDAtNzFiNTNiM2RkYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE3NTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNjNmYzg5NWYzMGM5YmQ2ZjAyNGIxMGMxM2Q4YjQ4MGI2Y2E2NTRlOGMxMTUwMWE4NGFhNTI2YTZhODI1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRVPDy-E6fQcQlxE3_OGaTPR32SNUqOnt6OLx55BsW4)

Okay I will fix it soon

**Comment by IAFahim** [comment]
> 8. Scriptable object to have a button near it to open in floating inspector mode or in Scriptable Wizard. Done in [Update Scriptable Wizard #88](https://github.com/pancake-llc/foundation/pull/88)

Can we have a shortcut for opening the `Scriptable Wizard` → **Ctrl + `** , same as Wizard → **Ctrl + w**

**Ctrl + `** is not in use and really stratifying to click

**Comment by yenmoc** [comment]
Actually I quite like Alt +... maybe it's just my hand, but anyway Unity already uses it so we'll live with crtl

**Comment by yenmoc** [comment]
> Sir, the UI is not that visible in light mode
> 
> ![image](https://private-user-images.githubusercontent.com/63500913/296829407-a5c7d966-9775-4869-8340-71b53b3ddc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTIwODMsIm5iZiI6MTcwNTM5MTc4MywicGF0aCI6Ii82MzUwMDkxMy8yOTY4Mjk0MDctYTVjN2Q5NjYtOTc3NS00ODY5LTgzNDAtNzFiNTNiM2RkYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDQzZTlhMDhhMGJiY2VjNmNiODA4OTRjYmNkOTYzZmM2NGM5Yjk0NjdmNTExMWMyYThlZmFhYTA5NDBlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqD_mSUUyGaJDbFGy-wwrrqy43lk9dOIAV0a7TH_9So)

Done with #98

**Comment by yenmoc** [comment]
@IAFahim  I've revised GameComponent as well as updated its documentation, which you can read [here](https://github.com/pancake-llc/foundation/wiki/GameComponent-x-GameLoop)

**Comment by IAFahim** [comment]
> @IAFahim I've revised GameComponent as well as updated its documentation, which you can read [here](https://github.com/pancake-llc/foundation/wiki/GameComponent-x-GameLoop)

It's Really Really Really helpful. Thank you, Sir.

**But I have a question now:**
Why are you removing all the GameCompent and defaulting back to Unity Loop in this project.

**Comment by greennatural** [comment]
@yenmoc 
Hello! I'm very impressed with this Unity game Platform. In the Advertising module, you should consider adding Native ad formats, as they are very effective when used in games, and you'll likely need them soon. Additionally, when displaying the app open format, you should hide the banner; after closing the app open format, the banner will be displayed again. I think you should incorporate this logic into some part of the platform. Have a great day!

**Comment by yenmoc** [comment]
Thank you for the clarification, I will add it to the next release
