### ISSUE TITLE
Documentation Improvement For Scriptable Architecture

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#89]
https://github.com/pancake-llc/foundation/wiki/scriptable-architecture#scriptable-list

- `The Additive Scene Loaded` Bullet Point is missing

![image](https://github.com/pancake-llc/foundation/assets/63500913/1f6ff31a-756e-4949-8ef9-d9eec2d97722)

I don't know how to contribute to the wiki, so putting it here.

**Comment by yenmoc** [comment]
Updated
