### ISSUE TITLE
Wiki Improvement For Anti Singleton

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#91]
https://github.com/pancake-llc/foundation/wiki/anti-singleton

avaiable -> available

![image](https://github.com/pancake-llc/foundation/assets/63500913/b8090445-f467-40df-82cd-023853a5f778)

usefull -> useful

![image](https://github.com/pancake-llc/foundation/assets/63500913/ae794b21-4f0a-408a-852b-1f7b7bf4e49c)

**Comment by yenmoc** [comment]
Done!
