### ISSUE TITLE
Error Importing Hearts

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#94]
The Editor script Didn't check for if the `PANCAKE_IAP` package was installed or not Fixed by adding

```csharp
#if PANCAKE_IAP

    ...existing code

#enif
```

`ScriptableEventIAPNoParamPropertyDrawer`
`ScriptableEventIAPNoParamDrawer`

Fixed in #93

**Comment by yenmoc** [comment]
Thanks
